[package]
name = "takeout_fixer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
gufo-exif = "0.1.3"
google-drive = "0.7.0"
zip = "2.2.1"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
