//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "takeout_zip")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub drive_id: String,
    pub name: String,
    pub local_path: String,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
